spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/myblogdb #${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: update
  flyway:
    baseline-on-migrate: true
app:
  jwtSecret: "topSecret"
  jwtExpirationInMs: 604800000